apiVersion: v1
kind: Service
metadata:
  name: mass-api
spec:
  type: {{ .Values.service.api.type }}
  selector:
    app: mass-api
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.port }}
