{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  data:
{{ toYaml .Values.externalSecret.data | indent 4 }}
{{- end }}
