apiVersion: v1
kind: Service
metadata:
  name: mass-web
spec:
  type: {{ .Values.service.web.type }}
  selector:
    app: mass-web
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.port }}
